CORE_DIR ?= $(patsubst %/,%,$(dir $(lastword $(MAKEFILE_LIST))))
ifeq ($(CORE_DIR),)
   CORE_DIR := .
endif

LIBRETRO_COMM_DIR := $(CORE_DIR)/extern/libretro-common

SOURCES_CXX := \
    $(CORE_DIR)/gb_core/apu.cpp \
    $(CORE_DIR)/gb_core/cheat.cpp \
    $(CORE_DIR)/gb_core/cpu.cpp \
    $(CORE_DIR)/gb_core/gb.cpp \
    $(CORE_DIR)/gb_core/lcd.cpp \
    $(CORE_DIR)/gb_core/mbc.cpp \
    $(CORE_DIR)/gb_core/rom.cpp \
    $(CORE_DIR)/gb_core/Infrared_Transceiver.cpp \
    $(CORE_DIR)/gb_core/GBPaletteManager.cpp \
    $(CORE_DIR)/libretro/dmy_renderer.cpp \
    $(CORE_DIR)/libretro/libretro.cpp \
    $(CORE_DIR)/gb_core/linkcable/alleyway_link_controller.cpp \
    $(CORE_DIR)/gb_core/linkcable/link_master_device.cpp \
    $(CORE_DIR)/gb_core/linkcable/linkcable_hub.cpp \
    $(CORE_DIR)/gb_core/linkcable/dmg07.cpp \
    $(CORE_DIR)/gb_core/linkcable/dmg07x4.cpp \
    $(CORE_DIR)/gb_core/linkcable/hack_4p_tetris.cpp \
    $(CORE_DIR)/gb_core/linkcable/hack_4p_kwirk.cpp \
    $(CORE_DIR)/gb_core/linkcable/hack_4p_burger_time_deluxe.cpp \
    $(CORE_DIR)/gb_core/linkcable/barcodeboy.cpp \
    $(CORE_DIR)/gb_core/linkcable/barcode_taisen_bardigun.cpp \
    $(CORE_DIR)/gb_core/linkcable/faceball2000_cable.cpp \
    $(CORE_DIR)/gb_core/linkcable/gameboy_printer.cpp \
    $(CORE_DIR)/gb_core/linkcable/game_and_watch_gallery_unlocker.cpp \
    $(CORE_DIR)/gb_core/linkcable/power_antenna.cpp \
    $(CORE_DIR)/gb_core/linkcable/pokebuddy_gen1.cpp \
    $(CORE_DIR)/gb_core/linkcable/Mobile_Adapter_GB.cpp \
    $(CORE_DIR)/gb_core/infrared/pikachu_2_gs.cpp \
    $(CORE_DIR)/gb_core/infrared/ubikey_unlocker.cpp \
    $(CORE_DIR)/gb_core/infrared/tv_remote.cpp \
    $(CORE_DIR)/gb_core/infrared/full_changer.cpp \
    $(CORE_DIR)/services/printer/bmp_printer.cpp \
    $(CORE_DIR)/services/printer/png_printer.cpp \
    $(CORE_DIR)/services/printer/image_scaler.cpp \
    $(CORE_DIR)/services/printer/printer_registry.cpp \
    $(CORE_DIR)/libretro/DoubleCherryEngine/Netplay/NetplayManager.cpp \
    $(CORE_DIR)/libretro/DoubleCherryEngine/Netplay/NetPacketManager.cpp \
    $(CORE_DIR)/libretro/DoubleCherryEngine/Netplay/NetPacketReceiveHandler.cpp \
    $(CORE_DIR)/libretro/DoubleCherryEngine/Netplay/NetPacketSendHandler.cpp \
    $(CORE_DIR)/libretro/DoubleCherryEngine/Netplay/NetpacketHandler/PokemonTcgNetpacketHandler.cpp


SOURCES_C := \
    $(LIBRETRO_COMM_DIR)/encodings/encoding_utf.c \
    $(LIBRETRO_COMM_DIR)/encodings/encoding_crc32.c \
    $(LIBRETRO_COMM_DIR)/net/net_socket.c \
    $(LIBRETRO_COMM_DIR)/net/net_compat.c \
    $(LIBRETRO_COMM_DIR)/net/net_http.c \
    $(LIBRETRO_COMM_DIR)/features/features_cpu.c \
    $(LIBRETRO_COMM_DIR)/time/rtime.c \
    $(LIBRETRO_COMM_DIR)/file/config_file.c \
    $(LIBRETRO_COMM_DIR)/file/file_path.c \
    $(LIBRETRO_COMM_DIR)/file/file_path_io.c \
    $(LIBRETRO_COMM_DIR)/file/retro_dirent.c \
    $(LIBRETRO_COMM_DIR)/compat/fopen_utf8.c \
    $(LIBRETRO_COMM_DIR)/lists/dir_list.c \
    $(LIBRETRO_COMM_DIR)/lists/string_list.c \
    $(LIBRETRO_COMM_DIR)/string/stdstring.c \
    $(LIBRETRO_COMM_DIR)/compat/compat_strl.c \
    $(LIBRETRO_COMM_DIR)/compat/compat_strcasestr.c \
    $(LIBRETRO_COMM_DIR)/streams/file_stream.c \
    $(LIBRETRO_COMM_DIR)/vfs/vfs_implementation.c

SOURCES_C += \
    $(CORE_DIR)/extern/libmobile/callback.c \
    $(CORE_DIR)/extern/libmobile/commands.c \
    $(CORE_DIR)/extern/libmobile/config.c \
    $(CORE_DIR)/extern/libmobile/debug.c \
    $(CORE_DIR)/extern/libmobile/dns.c \
    $(CORE_DIR)/extern/libmobile/inet_pton.c \
    $(CORE_DIR)/extern/libmobile/mobile.c \
    $(CORE_DIR)/extern/libmobile/relay.c \
    $(CORE_DIR)/extern/libmobile/serial.c \
    $(CORE_DIR)/extern/libmobile/util.c

INCFLAGS := -I$(abspath $(CORE_DIR)) \
            -I$(abspath $(CORE_DIR)/gb_core) \
            -I$(abspath $(CORE_DIR)/libretro) \
            -I$(abspath $(CORE_DIR)/extern/libretro-common/include) \
            -I$(abspath $(CORE_DIR)/extern/libmobile) \
            -isystem $(abspath $(CORE_DIR)/extern/libmobile) \
            -I$(abspath $(CORE_DIR)/extern/stb)

ifneq (,$(findstring msvc200,$(platform)))
    INCFLAGS += -I$(abspath $(LIBRETRO_COMM_DIR)/include/compat/msvc)
endif

DEFINES := -DBUILD_VERSION=\"$(GIT_VERSION)\" -D__LIBRETRO__ -DNDEBUG -DMOBILE_LIBCONF_USE
FLAGS += $(DEFINES)